// client/src/components/layout/Navbar.vue
<script setup>
import logo from '../../assets/lpl_logo.jpg';
import { Icon } from '@iconify/vue';
import { ref } from 'vue';

const emit = defineEmits(['toggle-sidebar']);
const navMenuOpen = ref(false);
</script>

<template>
  <header class="flex justify-between items-center sticky top-0 z-50   bg-primary shadow py-4 px-4 w-full">
    <!-- Left: Logo triggers SIDEBAR toggle -->
    <div class="flex items-center gap-2 cursor-pointer" @click="emit('toggle-sidebar')">
      <img :src="logo" alt="LPL Logo" class="w-10 h-10 rounded-full" />
      <h1 class="font-semibold text-lg text-black">LPL</h1>
    </div>

    <!-- Right: Desktop nav + mobile toggle -->
    <div class="flex items-center gap-6">
      <!-- Desktop nav -->
      <ul class="hidden sm:flex items-center gap-6 text-sm text-gray-700 font-medium">
        <li class="hover:text-blue-600 cursor-pointer">Home</li>
        <li class="hover:text-blue-600 cursor-pointer">About</li>
        <li class="hover:text-blue-600 cursor-pointer">Services</li>
        <li class="hover:text-blue-600 cursor-pointer">Contact</li>
      </ul>

        <!-- Toggle button (mobile only) -->
      <button class="sm:hidden" @click="navMenuOpen = !navMenuOpen">
        <Icon icon="teenyicons:menu-outline" class="w-7 h-7 text-black"  v-if="!navMenuOpen" />
        <Icon icon="radix-icons:cross-1" class="w-7 h-7 text-black" v-if="navMenuOpen" />
      </button>
    </div>
  </header>

  <!-- Mobile dropdown menu -->
  <div v-if="navMenuOpen" class="sm:hidden bg-primary px-4 py-2 shadow absolute top-12 right-8 z-50 rounded-md">
    <ul class="flex flex-col gap-2 text-sm text-gray-700 font-medium">
      <li class="hover:text-blue-600 cursor-pointer">Home</li>
      <li class="hover:text-blue-600 cursor-pointer">About</li>
      <li class="hover:text-blue-600 cursor-pointer">Services</li>
      <li class="hover:text-blue-600 cursor-pointer">Contact</li>
    </ul>
  </div>
</template>

// client/src/components/header/Navbar.tsx
import { useNavigate } from "react-router-dom"
import { assets } from "../../assets/assets"

const Navbar = () => {

  const navigate = useNavigate();
  return (
    <div className=" w-full flex justify-between items-center p-4 sm:p-6 sm:px-24 absolute top-0">

      <img src={assets.logo} alt="" className="w-12 sm:w-16 h-12 sm:h-16 rounded-full" />

      <button onClick={() => navigate('/auth/login')} className="flex items-center gap-2 border border-gray-500 rounded-full 
        px-6 py-2 text-gray-800 hover:bg-gray-100 transition-all">Login
        <img src={assets.arrow_icon} alt="" /></button>

    </div>
  )
}

export default Navbar
